// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/unknown.proto

package protobuf.codec.xml;

public final class UnknownProtoBuf {
  private UnknownProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(protobuf.codec.xml.UnknownProtoBuf.otherid);
    registry.add(protobuf.codec.xml.UnknownProtoBuf.lang);
  }
  public enum Lang
      implements com.google.protobuf.ProtocolMessageEnum {
    JAVA(0, 1),
    HASKELL(1, 2),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static Lang valueOf(int value) {
      switch (value) {
        case 1: return JAVA;
        case 2: return HASKELL;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Lang>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Lang>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Lang>() {
            public Lang findValueByNumber(int number) {
              return Lang.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protobuf.codec.xml.UnknownProtoBuf.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Lang[] VALUES = {
      JAVA, HASKELL, 
    };
    public static Lang valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private Lang(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      protobuf.codec.xml.UnknownProtoBuf.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:Lang)
  }
  
  public static final class Unknown extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Unknown> {
    // Use Unknown.newBuilder() to construct.
    private Unknown() {
      initFields();
    }
    private Unknown(boolean noInit) {}
    
    private static final Unknown defaultInstance;
    public static Unknown getDefaultInstance() {
      return defaultInstance;
    }
    
    public Unknown getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.codec.xml.UnknownProtoBuf.internal_static_Unknown_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.codec.xml.UnknownProtoBuf.internal_static_Unknown_fieldAccessorTable;
    }
    
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated .Version verions = 4;
    public static final int VERIONS_FIELD_NUMBER = 4;
    private java.util.List<protobuf.codec.xml.UnknownProtoBuf.Version> verions_ =
      java.util.Collections.emptyList();
    public java.util.List<protobuf.codec.xml.UnknownProtoBuf.Version> getVerionsList() {
      return verions_;
    }
    public int getVerionsCount() { return verions_.size(); }
    public protobuf.codec.xml.UnknownProtoBuf.Version getVerions(int index) {
      return verions_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!extensionsAreInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage.ExtendableMessage
        .ExtensionWriter extensionWriter = newExtensionWriter();
      if (hasName()) {
        output.writeString(1, getName());
      }
      for (protobuf.codec.xml.UnknownProtoBuf.Version element : getVerionsList()) {
        output.writeMessage(4, element);
      }
      extensionWriter.writeUntil(201, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      for (protobuf.codec.xml.UnknownProtoBuf.Version element : getVerionsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Unknown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.codec.xml.UnknownProtoBuf.Unknown prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          protobuf.codec.xml.UnknownProtoBuf.Unknown, Builder> {
      private protobuf.codec.xml.UnknownProtoBuf.Unknown result;
      
      // Construct using protobuf.codec.xml.UnknownProtoBuf.Unknown.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new protobuf.codec.xml.UnknownProtoBuf.Unknown();
        return builder;
      }
      
      protected protobuf.codec.xml.UnknownProtoBuf.Unknown internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new protobuf.codec.xml.UnknownProtoBuf.Unknown();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.codec.xml.UnknownProtoBuf.Unknown.getDescriptor();
      }
      
      public protobuf.codec.xml.UnknownProtoBuf.Unknown getDefaultInstanceForType() {
        return protobuf.codec.xml.UnknownProtoBuf.Unknown.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public protobuf.codec.xml.UnknownProtoBuf.Unknown build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private protobuf.codec.xml.UnknownProtoBuf.Unknown buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public protobuf.codec.xml.UnknownProtoBuf.Unknown buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.verions_ != java.util.Collections.EMPTY_LIST) {
          result.verions_ =
            java.util.Collections.unmodifiableList(result.verions_);
        }
        protobuf.codec.xml.UnknownProtoBuf.Unknown returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.codec.xml.UnknownProtoBuf.Unknown) {
          return mergeFrom((protobuf.codec.xml.UnknownProtoBuf.Unknown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.codec.xml.UnknownProtoBuf.Unknown other) {
        if (other == protobuf.codec.xml.UnknownProtoBuf.Unknown.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.verions_.isEmpty()) {
          if (result.verions_.isEmpty()) {
            result.verions_ = new java.util.ArrayList<protobuf.codec.xml.UnknownProtoBuf.Version>();
          }
          result.verions_.addAll(other.verions_);
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 34: {
              protobuf.codec.xml.UnknownProtoBuf.Version.Builder subBuilder = protobuf.codec.xml.UnknownProtoBuf.Version.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addVerions(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated .Version verions = 4;
      public java.util.List<protobuf.codec.xml.UnknownProtoBuf.Version> getVerionsList() {
        return java.util.Collections.unmodifiableList(result.verions_);
      }
      public int getVerionsCount() {
        return result.getVerionsCount();
      }
      public protobuf.codec.xml.UnknownProtoBuf.Version getVerions(int index) {
        return result.getVerions(index);
      }
      public Builder setVerions(int index, protobuf.codec.xml.UnknownProtoBuf.Version value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.verions_.set(index, value);
        return this;
      }
      public Builder setVerions(int index, protobuf.codec.xml.UnknownProtoBuf.Version.Builder builderForValue) {
        result.verions_.set(index, builderForValue.build());
        return this;
      }
      public Builder addVerions(protobuf.codec.xml.UnknownProtoBuf.Version value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.verions_.isEmpty()) {
          result.verions_ = new java.util.ArrayList<protobuf.codec.xml.UnknownProtoBuf.Version>();
        }
        result.verions_.add(value);
        return this;
      }
      public Builder addVerions(protobuf.codec.xml.UnknownProtoBuf.Version.Builder builderForValue) {
        if (result.verions_.isEmpty()) {
          result.verions_ = new java.util.ArrayList<protobuf.codec.xml.UnknownProtoBuf.Version>();
        }
        result.verions_.add(builderForValue.build());
        return this;
      }
      public Builder addAllVerions(
          java.lang.Iterable<? extends protobuf.codec.xml.UnknownProtoBuf.Version> values) {
        if (result.verions_.isEmpty()) {
          result.verions_ = new java.util.ArrayList<protobuf.codec.xml.UnknownProtoBuf.Version>();
        }
        super.addAll(values, result.verions_);
        return this;
      }
      public Builder clearVerions() {
        result.verions_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Unknown)
    }
    
    static {
      defaultInstance = new Unknown(true);
      protobuf.codec.xml.UnknownProtoBuf.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Unknown)
  }
  
  public static final class Version extends
      com.google.protobuf.GeneratedMessage {
    // Use Version.newBuilder() to construct.
    private Version() {
      initFields();
    }
    private Version(boolean noInit) {}
    
    private static final Version defaultInstance;
    public static Version getDefaultInstance() {
      return defaultInstance;
    }
    
    public Version getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.codec.xml.UnknownProtoBuf.internal_static_Version_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.codec.xml.UnknownProtoBuf.internal_static_Version_fieldAccessorTable;
    }
    
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.codec.xml.UnknownProtoBuf.Version parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.codec.xml.UnknownProtoBuf.Version prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private protobuf.codec.xml.UnknownProtoBuf.Version result;
      
      // Construct using protobuf.codec.xml.UnknownProtoBuf.Version.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new protobuf.codec.xml.UnknownProtoBuf.Version();
        return builder;
      }
      
      protected protobuf.codec.xml.UnknownProtoBuf.Version internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new protobuf.codec.xml.UnknownProtoBuf.Version();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.codec.xml.UnknownProtoBuf.Version.getDescriptor();
      }
      
      public protobuf.codec.xml.UnknownProtoBuf.Version getDefaultInstanceForType() {
        return protobuf.codec.xml.UnknownProtoBuf.Version.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public protobuf.codec.xml.UnknownProtoBuf.Version build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private protobuf.codec.xml.UnknownProtoBuf.Version buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public protobuf.codec.xml.UnknownProtoBuf.Version buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        protobuf.codec.xml.UnknownProtoBuf.Version returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.codec.xml.UnknownProtoBuf.Version) {
          return mergeFrom((protobuf.codec.xml.UnknownProtoBuf.Version)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.codec.xml.UnknownProtoBuf.Version other) {
        if (other == protobuf.codec.xml.UnknownProtoBuf.Version.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Version)
    }
    
    static {
      defaultInstance = new Version(true);
      protobuf.codec.xml.UnknownProtoBuf.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Version)
  }
  
  public static final int OTHERID_FIELD_NUMBER = 101;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      protobuf.codec.xml.UnknownProtoBuf.Unknown,
      java.lang.Integer> otherid =
        com.google.protobuf.GeneratedMessage
          .newGeneratedExtension();
  public static final int LANG_FIELD_NUMBER = 102;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      protobuf.codec.xml.UnknownProtoBuf.Unknown,
      java.util.List<protobuf.codec.xml.UnknownProtoBuf.Lang>> lang =
        com.google.protobuf.GeneratedMessage
          .newGeneratedExtension();
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Unknown_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Unknown_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Version_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Version_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/test/resources/unknown.proto\"9\n\007Un" +
      "known\022\014\n\004name\030\001 \001(\t\022\031\n\007verions\030\004 \003(\0132\010.V" +
      "ersion*\005\010d\020\311\001\"\027\n\007Version\022\014\n\004name\030\001 \001(\t*\035" +
      "\n\004Lang\022\010\n\004JAVA\020\001\022\013\n\007HASKELL\020\002:\031\n\007otherid" +
      "\022\010.Unknown\030e \001(\005:\035\n\004lang\022\010.Unknown\030f \003(\016" +
      "2\005.LangB%\n\022protobuf.codec.xmlB\017UnknownPr" +
      "otoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Unknown_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Unknown_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Unknown_descriptor,
              new java.lang.String[] { "Name", "Verions", },
              protobuf.codec.xml.UnknownProtoBuf.Unknown.class,
              protobuf.codec.xml.UnknownProtoBuf.Unknown.Builder.class);
          internal_static_Version_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Version_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Version_descriptor,
              new java.lang.String[] { "Name", },
              protobuf.codec.xml.UnknownProtoBuf.Version.class,
              protobuf.codec.xml.UnknownProtoBuf.Version.Builder.class);
          protobuf.codec.xml.UnknownProtoBuf.otherid.internalInit(
              protobuf.codec.xml.UnknownProtoBuf.getDescriptor().getExtensions().get(0),
              java.lang.Integer.class);
          protobuf.codec.xml.UnknownProtoBuf.lang.internalInit(
              protobuf.codec.xml.UnknownProtoBuf.getDescriptor().getExtensions().get(1),
              protobuf.codec.xml.UnknownProtoBuf.Lang.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
